var a = [1, 12, 93, 5];
var b = ["a", "apricot", "mango"];
//let c: number[] = [1,"apple","potato"];
var d = [null, undefined, 10, 15];
var ef = ["pie", null, ""];
var ab = [1, 12, 93, 5];
var bb = ["a", "apricot", "mango"];
//let cc: number[] = [1, "apple", "potato"]; 
var dd = [null, undefined, 10, 15];
var ee = ["pie", null, ""];
console.log(a[1]);
console.log(b[2]);
